---
/**:
  hazards_vector_publisher:
    ros__parameters:
      # Hazard detection publisher topic
      publisher_topic: hazard_detection
      publish_rate: 62.0
      subscription_topics:
        # Bumper topic
        - _internal/bumper/event
        # Cliff topics
        - _internal/cliff_front_left/event
        - _internal/cliff_front_right/event
        - _internal/cliff_side_left/event
        - _internal/cliff_side_right/event
        # Wheel drop topics
        - _internal/wheel_drop/left_wheel/event
        - _internal/wheel_drop/right_wheel/event
        # Backup limit topic
        - _internal/backup_limit
