---
/**:
  ir_intensity_vector_publisher:
    ros__parameters:
      # IR intensity publisher topic
      publisher_topic: ir_intensity
      publish_rate: 62.0
      subscription_topics:
        # IR intensity topics
        - _internal/ir_intensity_front_center_left
        - _internal/ir_intensity_front_center_right
        - _internal/ir_intensity_front_left
        - _internal/ir_intensity_front_right
        - _internal/ir_intensity_left
        - _internal/ir_intensity_right
        - _internal/ir_intensity_side_left
