---
/**:
  wheel_status_publisher:
    ros__parameters:
      # Publish rate
      publish_rate: 62.0
      # Encoder resolution
      encoder_resolution: 508.8
      # Wheel radius
      wheel_radius: 0.03575
      # Wheels angular velocity topic
      velocity_topic: wheel_vels
      # Wheels' net encoder ticks topic
      ticks_topic: wheel_ticks
